spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false