spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vdt?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 15122004
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8084